### ISSUE TITLE
Tests are present for Role, Lookup Plugin, and Module

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/ansible-role-conjur#25]
Prior to releasing to Galaxy, we need to provide a minimal level of testing for the role, lookup plugin, and module, to insure they work as expected.  

These tests should follow the Ansible convention, and use Molecule.  Due to the tight timeline, these tests to not need to be runnable in Jenkins.  That will be covered in a future story.

**Comment by InbalZilberman** [comment]
Please share test plan with the team before finishing this task. 
Please make sure this test plan is reviewed by team and PO.
Please update the test plan with scenarios that were part of the automation test.
