### ISSUE TITLE
Jenkins Pipeline exists and green to run tests

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/ansible-role-conjur#27]
To integrate this project into our CI/CD pipeline, we'll need to make sure we can run the suite of Molecule tests on Jenkins. If at all possible, we'd like to avoid installing any new dependencies on our Jenkins Executors.  The preferred approach is to use Docker containers to encapsulate additional dependencies.

**Comment by orenbm** [comment]
We need the controller to run Ansible (2.3.x.x) and Molecule (2.x.x)

**Comment by ghost** [comment]
This was addressed and merged in https://github.com/cyberark/ansible-role-conjur/pull/53, closing this issue.
