### ISSUE TITLE
Demo running Conjur role to get a Conjur identity. Using this identity show that a secret was retrieved using summon

### ISSUE THREAD

**Issue by orenbm** [cyberark/ansible-role-conjur#3]

**Comment by orenbm** [comment]
At this point the demo retrieves a secret from Conjur, in the target container, with Conjur cli.

We would like to fetch secrets with Summon too as this is a common scenario

**Comment by jeniaSakirko** [comment]
#18 @doodlesbykumbi Created a demo with summon
