### ISSUE TITLE
Ansible Plugin for fetching Secrets on top of Conjur v5

### ISSUE THREAD

**Issue by orenbm** [cyberark/ansible-role-conjur#9]
Feature details: https://conjurinc.atlassian.net/browse/CUB-46

**Comment by jvanderhoof** [comment]
This is going to be the big beefy part of moving to v5.  I'm working on the README for this role here: https://github.com/cyberark/ansible-role-conjur/blob/conjur-5/README.md.

This is the proposed lookup functionality:
```yml
- hosts: webservers
  vars:
    super_secret_key: {{ lookup('conjur', 'path/to/secret') }} 
    max_clients: 200
  remote_user: root
  tasks:
    ...
```
All lookups are executed on the host, not the remote, which complicates things a bit.  It means the identity of the remote are not usable when retrieving secrets from Conjur.  It also means the Ansible host needs to have permission to retrieve all referenced secrets. Ultimately, we'd like secret retrieval to use the remote node's identity, not the host's identity.

Before we start coding, I really think we need to spend some time researching and understanding the tradeoffs of various approaches.  Here are a couple of options I see:
* Write a lookup plugin that uses the host identity to retrieve secrets for remote (not great, means over-privileging ansible).
* Install `conjur-summon` on remote machines and figure out how to remotely execute a call to it as part of a service startup/restart (better, but requires installing an extra library, which people may not be psyched about).
* Figure out how to execute remote calls (without an external library) to set environment variables or an in memory file.

**Comment by ghost** [comment]
I believe the python stdlib has everything we need. I think we also get all of Ansible's dependencies for free too, like `requests`.
